### ISSUE TITLE
IndexError when the string provided between eleven to nineteen

### ISSUE THREAD

**Issue by sanjay75409** [akshaynagpal/w2n#2]
print w2n.word_to_num("eleven")

Traceback (most recent call last):
  File "<pyshell#3>", line 1, in <module>
    print w2n.word_to_num("eleven")
  File "C:\Python27\lib\site-packages\word2number\w2n.py", line 98, in word_to_num
    hundreds = number_formation(clean_numbers)
  File "C:\Python27\lib\site-packages\word2number\w2n.py", line 120, in number_formation
    return numbers[0]
IndexError: list index out of range

print w2n.word_to_num("nineteen")

Traceback (most recent call last):
  File "<pyshell#2>", line 1, in <module>
    print w2n.word_to_num("nineteen")
  File "C:\Python27\lib\site-packages\word2number\w2n.py", line 98, in word_to_num
    hundreds = number_formation(clean_numbers)
  File "C:\Python27\lib\site-packages\word2number\w2n.py", line 120, in number_formation
    return numbers[0]
IndexError: list index out of range

**Comment by akshaynagpal** [comment]
Thanks for pointing this issue @sanjay75409 . I must have missed this while testing. I will look into this in the next version release. Also, you are most welcome to contribute and resolve this issue.

**Comment by akshaynagpal** [comment]
Solved by pull request  #4 by @tyarkoni !
